language: python
os: linux
dist: jammy
python:
  - "3.11"

install:
  - gem install webrick
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls
  - mkdir ./tools
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./tools

script:
  - black . --check
  - flake8 --max-line-length=88
  - coverage run --source=swe_app,polls manage.py test
  - coverage xml
  - ./tools/coveralls report --repo-token=$COVERALLS_REPO_TOKEN ./coverage.xml

deploy:
  - provider: elasticbeanstalk
    access_key_id: "AKIAYIMDP2GLJASYR4ND"
    secret_access_key: "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"
    region: "us-west-2"
    app: "swe_app2"
    env: "swe-app-env2"
    bucket_name: "elasticbeanstalk-us-west-2-567748317590"
    on:
      branch: main