language: python
os: linux
dist: jammy
python:
  - "3.11"

install:
  - gem install webrick
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coveralls
  - mkdir ./tools
  - curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C ./tools

script: true

deploy:
  - provider: elasticbeanstalk
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-west-2"
    app: "swe_app1"
    env: "swe-app-env1"
    bucket_name: "elasticbeanstalk-us-west-2-567748317590"
    on:
      branch: main