branch-defaults:
  main:
    environment: swe-app-env1
    group_suffix: null
global:
  application_name: swe_app1
  branch: null
  default_ec2_keyname: test
  default_platform: Python 3.11
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
